package kr.co.pionnet.scdev4.bot.domain.restaurant.entity;

public enum LunchMentAnimationEnum {
    LUNCH0("CgACAgQAAxkBAAIVQ2q7fgABM4_2ngABdSfY1eDfzwPR3eAAAh8IAAJe9IRSuUu61TQi3xs9BA"),
    LUNCH1("CgACAgQAAxkBAAIVQmq7ff0V-G8_KBgpBmmOnkdj3D9dAALLnwACjR5kBzuPWixsHKl2PQQ"),
    LUNCH2("CgACAgQAAxkBAAIVQWq7ffuTzBQ-7-fON0qIu8fGMtN1AAIDBAAC4odtUwM9kY3SdoqlPQQ"),
    LUNCH3("CgACAgQAAxkBAAIVQGq7ffquBc8e3HUtcf_qs6jQMap4AAKsBAACfmcVUQvGL9tOtjzYPQQ"),
    LUNCH4("CgACAgQAAxkBAAIVP2q7ffhEPX6i5SziESZXs6glQrMdAAIEBAAC6zQlUbfofCLiyPRkPQQ"),
    LUNCH5("CgACAgQAAxkBAAIVPmq7ffbXObiHD__-KhpU_GCr62Y8AAKGCgADd6RQfsiJAeF1xMU9BA"),
    LUNCH6("CgACAgQAAxkBAAIVPWq7ffSbQH-f_5jwJRCV5gRQYWAcAALyCQACdCLFUKVTMgb-e8RiPQQ"),
    LUNCH7("CgACAgQAAxkBAAIVPGq7ffNfBJ72dQQLgkJAbQoUmbGtAAKgBQACWw0kUbkaHAqeiwABGj0E"),
    LUNCH8("CgACAgQAAxkBAAIVO2q7ffIkGT-NPDuenEHju8-zhS1vAAKZCgAC9dn1UzHIa9P63NTlPQQ"),
    LUNCH9("CgACAgQAAxkBAAIVOmq7ffCgLITqOHnp-85BsFCUuij-AAKqCgACFSN0Uc_1K7TqAySTPQQ"),
    LUNCH10("CgACAgQAAxkBAAIVOWq7fe8D3yLrxL4rJ-Ko0gQM97kZAALtCgACJMCkUE1p6SlStRtJPQQ"),
    LUNCH11("CgACAgQAAxkBAAIVOGq7fe2ln_cS0IvhD3IKqh4ZnyBiAAJjCwACOIycUKbSImjHpNGdPQQ"),
    LUNCH12("CgACAgQAAxkBAAIVN2q7fexvfAbGLfqxJgpkEUFIxPnxAAK4BgACRbREUqm9h-WmCEz0PQQ"),
    LUNCH14("CgACAgQAAxkBAAIVLGq7fVkRutXFb8phdzclGLHa3Mu-AALUCgACvJWcUOBIXbYspgblPQQ"),
    LUNCH15("CgACAgQAAxkBAAIVNmq7fevO-r8oalBXlSE4oQfw02tWAAKLCgACVWHEULLAwng1adc7PQQ"),
    LUNCH16("CgACAgQAAxkBAAIVNWq7fekX1A_yQkvtTziuEYOyaaaYAAL1AgACuNEMUzmozl-aM_a8PQQ"),
    LUNCH17("CgACAgQAAxkBAAIVNGq7fefFfoQL0-S8fM73-2VPBaxYAAJlBQACgGQMU5ekgenGgWi4PQQ"),
    LUNCH18("CgACAgQAAxkBAAIVM2q7feUHr2e2hDywIh3ddcX8jC3_AALGCgACCGSlUHj-8WHz5kjGPQQ");

    private final String value;

    LunchMentAnimationEnum(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }
}
